// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjHnF9sa2Hywy3qM_SFrBgHrteJbXJgSc',
    appId: '1:930545950628:web:035dc0638f78ac91b56b31',
    messagingSenderId: '930545950628',
    projectId: 'tablecalender-6998a',
    authDomain: 'tablecalender-6998a.firebaseapp.com',
    storageBucket: 'tablecalender-6998a.appspot.com',
    measurementId: 'G-KFQPJHVHRR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsQZeJxcaQLeFQ5S0PUsq_KntFvDFJ1Xc',
    appId: '1:930545950628:android:72b5469bc47f15cbb56b31',
    messagingSenderId: '930545950628',
    projectId: 'tablecalender-6998a',
    storageBucket: 'tablecalender-6998a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD83AZ8o_7_aLDOU2xIWAWKcggQQWbKpoM',
    appId: '1:930545950628:ios:1974552451e23682b56b31',
    messagingSenderId: '930545950628',
    projectId: 'tablecalender-6998a',
    storageBucket: 'tablecalender-6998a.appspot.com',
    iosBundleId: 'com.example.tableCalenderEvent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD83AZ8o_7_aLDOU2xIWAWKcggQQWbKpoM',
    appId: '1:930545950628:ios:57c97614836f17b2b56b31',
    messagingSenderId: '930545950628',
    projectId: 'tablecalender-6998a',
    storageBucket: 'tablecalender-6998a.appspot.com',
    iosBundleId: 'com.example.tableCalenderEvent.RunnerTests',
  );
}
